[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python app.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "5000"
FLASK_ENV = "production"
PYTHON_VERSION = "3.10"

[services.backend]
source = "backend/" 